# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5824628e7c6867367447cd9fb9a61e44a78acc384d31a7b82eadf3d3d55dd2d5032a4953446af199ea0c595b248b3950e555d5f2733a35dadffadaeb1b5b9d9b

test:
  secret_key_base: 58ef0058006987ce0f2a00ccc05cc8694720061c41379133b9cff179282081ee92b465ef05a2faa6b008c6dfed0ad024292769e371346db1208ce9c689dfcdf6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
